spring.application.name=bff

server.port=8080

url.platform=http://ec2-44-203-162-100.compute-1.amazonaws.com:8080/api/v1/platforms
url.repo=http://ec2-3-80-255-213.compute-1.amazonaws.com:8080/api/v1/repositories

app.sqs.attendee-events-url=https://sqs.us-east-1.amazonaws.com/289170824875/idat-web-sqs.fifo

spring.cloud.aws.sqs.queue-not-found-strategy= FAIL
spring.cloud.aws.region.static=us-east-1

