spring.application.name=bff

server.port=8080

url.platform=http://ec2-44-203-162-100.compute-1.amazonaws.com:8080/api/v1/platforms
url.repo=http://ec2-3-80-255-213.compute-1.amazonaws.com:8080/api/v1/repositories